In [8]:
list1 = [5,8,2,4,7,9]
Sum = sum(list1)
print (Sum)

35


In [11]:
import numpy
list2 = [4,3,5,6,2]
Multiply = numpy.prod(list2)
print(Multiply)

720


In [19]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [21]:
#a) Sort the flattened array
print('array_hw:')
print(array_hw)
print('')
print('flattened array_hw:')
flat_array_hw=array_hw.flatten()
print(flat_array_hw)

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

flattened array_hw:
[5 5 8 8 9 8 7 7 5 3 5 7 8 7 8 4 2 6 9 9 7 3 1 4]


In [22]:
#b) Sort the second column
print('array_hw:')
print(array_hw)
print('')
print('second column of array_hw:')
print(array_hw[...,1])

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

second column of array_hw:
[5 7 7 9]


In [23]:
#c) Sort the third row
print('array_hw:')
print(array_hw)
print('')
print('third row of array_hw:')
print(array_hw[2,...])

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

third row of array_hw:
[8 7 8 4 2 6]


In [25]:
#d) Extract the second row onwards
print('array_hw:')
print(array_hw)
print('')
print('first two rows of array_hw:')
print(array_hw[:2,...])

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

first two rows of array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]]


In [28]:
#e) Extract the third column onwards
print('array_hw:')
print(array_hw)
print('')
print('first three columns of array_hw:')
print(array_hw[...,:3])

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

first three columns of array_hw:
[[5 5 8]
 [7 7 5]
 [8 7 8]
 [9 9 7]]


In [41]:
#f) obtain the square of array_hw
print(array_hw**2)

[[25 25 64 64 81 64]
 [49 49 25  9 25 49]
 [64 49 64 16  4 36]
 [81 81 49  9  1 16]]


In [33]:
#g)Slice the element from the third row and fourth column position 3X4
print('array_hw:')
print(array_hw)
print('')
print('element sliced from third row and fourth column:')
print(array_hw[2,3])

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

element sliced from third row and fourth column:
4


In [34]:
# f) obtain the total sum of array_hw
array_hw.sum()

145

In [35]:
# h) How many dimentions does array_hw have?
array_hw.ndim

2

In [39]:
# i) What is the data type listed in array_hw?
array_hw.dtype

dtype('int32')

In [40]:
# j) What is the size of the memory in bytes consumed by all the elements in array_hw?
array_hw.size

24